#!/bin/sh
set -eu

ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"

: "${DEVELOPMENT_TEAM:?Set DEVELOPMENT_TEAM in Xcode Cloud environment variables}"
: "${PSH_BUNDLE_IDENTIFIER:?Set PSH_BUNDLE_IDENTIFIER in Xcode Cloud environment variables}"

cat > "$ROOT/Config.xcconfig" <<EOF
// Generated by Xcode Cloud
DEVELOPMENT_TEAM = $DEVELOPMENT_TEAM
PSH_BUNDLE_IDENTIFIER = $PSH_BUNDLE_IDENTIFIER
EOF

