default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    run_tests(
      project: "psh.xcodeproj",
      scheme: "psh",
      device: "iPhone 17",
      clean: true
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "psh.xcodeproj"
    )

    build_app(
      project: "psh.xcodeproj",
      scheme: "psh",
      configuration: "Release",
      destination: "generic/platform=iOS",
      clean: true,
      export_method: "app-store"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key_path: "fastlane/api_key.json"
    )
  end
end
